[package]
name = "oxipipe"
version = "0.1.0"
edition = "2024"

[dependencies]
bollard = "0.18.1"
env_logger = "0.11.8"
futures = "0.3.31"
log = "0.4.27"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
tokio = { version = "1.44.2", features = ["full"] }

