[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
serde.workspace = true
serde_yaml.workspace = true
bollard.workspace = true
futures.workspace = true
tracing.workspace = true
clap.workspace = true