jobs:
  hello:
    image: alpine:latest
    environment:
      - "NAME=Benny"
    command: ["sh", "-c", "echo $NAME > /workspace/test.txt"]
    artifacts: "/workspace"
    schedule: "@every 10s"
    triggers: 
      - bye
  bye:
    image: alpine:latest
    command: ["sh", "-c", "echo Bye $(cat /artifacts/hello/test.txt)"]
    dependencies:
      - hello
